// GET http://localhost:5243

###
GET http://localhost:5243/game

###
GET http://localhost:5243/game/1

###
POST http://localhost:5243/game
Content-Type: application/json

{
    "name" : "Bloodborne dpghrtkhgorkhoktrophkokrojurktypjokrtjk6jofdohphrokdrokpohkr",
    "genre" : "Action-RPG",
    "price" : "599.99",
    "releaseDate" : "2015-03-24"
}

###
PUT http://localhost:5243/game/1
Content-Type: application/json

{
    "name" : "Street Fighter VI",
    "genre" : "Fighting",
    "price" : "1099.99",
    "releaseDate" : "2023-06-02"
}

###
DELETE http://localhost:5243/game/5
