// GET http://localhost:5243

###
GET http://localhost:5243/game

###
GET http://localhost:5243/game/1

###
POST http://localhost:5243/game
Content-Type: application/json

{
    "name" : "SF6",
    "genreId" : 1,
    "price" : "999.99",
    "releaseDate" : "2024-07-15"
}

###
PUT http://localhost:5243/game/1
Content-Type: application/json

{
    "name" : "Street Fighter 5: Champion Edition",
    "genreId" : 1,
    "price" : "399.99",
    "releaseDate" : "1994-06-02"
}

###
DELETE http://localhost:5243/game/1